name: AdvancedGroup
version: 1.0.3-PRE-RELEASE
authors:
  - MoonTeam
  - Zoumi
main: MoonTeam\AdvancedGroup\Main
api: 4.0.0
softdepend:
  - SimpleFaction
  - FactionsPro
  - PiggyFactions
  - RedSkyBlock
  - SkyBlock

permissions:
  ag.addgroup:
    default: op
  ag.removegroup:
    default: op
  ag.addgperm:
    default: op
  ag.addpperm:
    default: op
  ag.groups:
    default: op
  ag.setformat:
    default: op
  ag.setgroup:
    default: op
  ag.listgperms:
    default: op
  ag.listpperms:
    default: op
  ag.removegperm:
    default: op
  ag.removepperm:
    default: op