name: AdvancedGroup
version: 1.0.0-PRE-RELEASE
authors:
  - MoonTeam
  - Zoumi
main: MoonTeam\AdvancedGroup\Main
api: 3.0.0

permissions:
  ag.addgroup:
    description: ""
  ag.removegroup:
    description: ""
  ag.addgperm:
    description: ""
  ag.addpperm:
    description: ""
  ag.groups:
    description: ""
  ag.setformat:
    description: ""
  ag.setgroup:
    description: ""
  ag.listgperm:
    description: ""
  ag.listpperm:
    description: ""
  ag.removegperm:
    description: ""
  ag.removepperm:
    description: ""